# Generated by Django 5.0.7 on 2024-07-09 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 9, 23, 43, 40, 168484, tzinfo=datetime.timezone.utc)),
        ),
    ]
