# Generated by Django 5.0.7 on 2024-07-10 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_tasks_accomplishments_alter_tasks_blockers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='editable',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 10, 2, 39, 50, 190484, tzinfo=datetime.timezone.utc)),
        ),
    ]
