# Generated by Django 5.0.7 on 2024-07-10 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_tasks_editable_alter_tasks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='accomplishments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='blockers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 10, 18, 56, 12, 729724, tzinfo=datetime.timezone.utc)),
        ),
    ]
